//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotsBpHelper.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotsBpHelper.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto detect 的本地化字符串。
        /// </summary>
        public static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto detect hero and map 的本地化字符串。
        /// </summary>
        public static string AutoDetectHeroAndMap {
            get {
                return ResourceManager.GetString("AutoDetectHeroAndMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto show/hide helper 的本地化字符串。
        /// </summary>
        public static string AutoShowHideHelper {
            get {
                return ResourceManager.GetString("AutoShowHideHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flies 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot update files, please try again. 的本地化字符串。
        /// </summary>
        public static string FilesNotReady {
            get {
                return ResourceManager.GetString("FilesNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string FileStatus {
            get {
                return ResourceManager.GetString("FileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update files 的本地化字符串。
        /// </summary>
        public static string FileUpdate {
            get {
                return ResourceManager.GetString("FileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get file list failed, please try again. 的本地化字符串。
        /// </summary>
        public static string GetFileListFailed {
            get {
                return ResourceManager.GetString("GetFileListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BP Helper 的本地化字符串。
        /// </summary>
        public static string HotsBpHelper {
            get {
                return ResourceManager.GetString("HotsBpHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No match resolution, cannot start the client. 的本地化字符串。
        /// </summary>
        public static string MSG_NoMatchResolution {
            get {
                return ResourceManager.GetString("MSG_NoMatchResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [NoChose] 的本地化字符串。
        /// </summary>
        public static string NO_CHOOSE {
            get {
                return ResourceManager.GetString("NO_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register hotkey failed, please use system tray. 的本地化字符串。
        /// </summary>
        public static string RegisterHotKeyFailed {
            get {
                return ResourceManager.GetString("RegisterHotKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show / Hide BPHelper 的本地化字符串。
        /// </summary>
        public static string ShowHideHelper {
            get {
                return ResourceManager.GetString("ShowHideHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update failed 的本地化字符串。
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find new version, ready to update. 的本地化字符串。
        /// </summary>
        public static string UpdatesAvailable {
            get {
                return ResourceManager.GetString("UpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update failed: {0} 的本地化字符串。
        /// </summary>
        public static string UpdatesFailed {
            get {
                return ResourceManager.GetString("UpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updating... 的本地化字符串。
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recognized 的本地化字符串。
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
